#!/bin/sh

##
# party
# Written by Joakim Sandman, October 2015.
# Last update: 7/10-15.
# Lab 1: Chattserver, Datakommunikation och datornät HT15.
# This script starts up 10 chat servers to populate the name server.
# It then kills them all after some time has passed.
##

# Run: ./party
# Run without standard output: ./party >/dev/null
# Run without any output: ./party >/dev/null 2>&1
# Kill (manually): killall server

# Enable job control
set -m

# Start up 10 instances of server and store their pids
./server "Anti-SkyNet" 51515 &
pid1=$!
./server "Joshua - \"The only winning move is not to play\"" 51516 &
pid2=$!
./server "Transhumanism (H+)" 51517 &
pid3=$!
./server "Epistemological Cyberneticist" 51518 &
pid4=$!
./server "Þursa-smiðja" 51519 &
pid5=$!
./server "¬(µæłø ∨ (Ω»¦«¥⅝²ß)) ∧ ©" 51520 &
pid6=$!
./server "All your base..." 51521 &
pid7=$!
./server "...are belong to us!" 51522 &
pid8=$!
./server " " 51523 &
pid9=$!
./server "GLaDOS (Friendly Edition)" 51524 &
pid0=$!
# Add   >/dev/null 2>&1   before the &'s above to suppress output

# Let them run for some time, unless manually killed
sleep 3d

# KIll all instances of server
kill $pid1
kill $pid2
kill $pid3
kill $pid4
kill $pid5
kill $pid6
kill $pid7
kill $pid8
kill $pid9
kill $pid0
#killall server

>&2 echo
>&2 echo
>&2 echo "***** All servers terminated! *****"
>&2 echo

exit 0;

